



local T = lib_towns.schems.T


return {
	size = {x = 9,y = 11,z = 11},
	data = {
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "default:grass_1",prob = 254},
		{param2 = 0,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 0,name = "default:grass_3",prob = 254},
		T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:drystack_stairs",prob = 254},
		{param2 = 1,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "default:grass_3",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:hearth",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:hearth_air",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:drystack_stairs",prob = 254},
		T["_____"], {param2 = 3,name = "earthbuild:drystack_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "default:furnace",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 2,name = "default:furnace",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 23,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 21,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:turf_slab",prob = 254},
		{param2 = 2,name = "earthbuild:drystack_stairs",prob = 254},
		{param2 = 0,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 23,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 21,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 20,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "earthbuild:primitive_bed_top",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 23,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 21,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "earthbuild:primitive_bed_bottom",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 23,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 21,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 2,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "default:chest",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:chest",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 23,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 21,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 2,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 2,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:primitive_bed_bottom",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 23,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 21,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 2,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 2,name = "lib_ecology:tree_aspen_wood_slab",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:primitive_bed_top",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 23,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 21,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 22,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "doors:door_wood_a",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 2,name = "doors:hidden",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 1,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 1,name = "default:aspen_wood",prob = 254},
		{param2 = 3,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 3,name = "earthbuild:turf_slab",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 2,name = "earthbuild:drystack_stairs",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "default:grass_4",prob = 254},
		T["_____"], {param2 = 0,name = "flowers:dandelion_white",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf_and_drystack",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "default:grass_4",prob = 254},
		T["_____"], T["_____"], T["_____"], {param2 = 0,name = "default:grass_3",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "earthbuild:turf",prob = 254},
		{param2 = 0,name = "default:grass_4",prob = 254},
		{param2 = 2,name = "earthbuild:turf_stairs",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], {param2 = 2,name = "earthbuild:turf_stairs",prob = 254},
		{param2 = 0,name = "default:grass_1",prob = 254},
		T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"], T["_____"],
	},
	yslice_prob = {
		{prob = 254,ypos = 0},
		{prob = 254,ypos = 1},
		{prob = 254,ypos = 2},
		{prob = 254,ypos = 3},
		{prob = 254,ypos = 4},
		{prob = 254,ypos = 5},
		{prob = 254,ypos = 6},
		{prob = 254,ypos = 7},
		{prob = 254,ypos = 8},
		{prob = 254,ypos = 9},
		{prob = 254,ypos = 10}
	}
}