

local T = lib_towns.schems.T

--Air, Lava, and Water constants used throughout schematics
	local __ = T["_____"] or {name = "air", param2 = 0, prob = 254}



return {
	size = {x = 13,y = 20,z = 13},
	data = {
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, T["W0L00"], __, T["W0L00"], __, T["W0L00"], __, T["W0L00"], __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, T["W0L00"], __, T["W0L00"], __, T["W0L00"], __, T["W0L00"], __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, T["W0L22"], __, T["W0L22"], __, T["W0L22"], __, T["W0L22"], __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "doors:door_wattle_a", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, __, __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "doors:hidden", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform_with_brush", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 23, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 23, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 22, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:basket", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 3, name = "earthbuild:primitive_bed_top", prob = 254},
		{param2 = 3, name = "earthbuild:primitive_bed_bottom", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 1, name = "earthbuild:primitive_bed_bottom", prob = 254},
		{param2 = 1, name = "earthbuild:primitive_bed_top", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:bottlegourd_cup", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:stair_cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_container", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 5, name = "default:ladder_wood", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 5, name = "default:ladder_wood", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:bottlegourd_container", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 5, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 2, name = "earthbuild:trapdoor_wattle", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 5, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_container", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 5, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, T["W0L21"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 5, name = "default:torch_wall", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 5, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		T["W0L23"], __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:stair_cob", prob = 254},
		{param2 = 2, name = "earthbuild:trapdoor_wattle", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:cob", prob = 254},
		T["Ld0W0"], __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_container", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		T["Ld0W0"], __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "earthbuild:bottlegourd_cup", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		T["Ld0W0"], {param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 3, name = "earthbuild:trapdoor_wattle", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, __, __, {param2 = 22, name = "stairs:slab_mud_brick", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 20, name = "stairs:slab_mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		__, {param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		{param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 1, name = "default:torch", prob = 254},
		__, __, __, {param2 = 1, name = "default:torch", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:basket", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_cup", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, T["W0L21"], {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		T["W0L23"], __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 21, name = "stairs:slab_mud_brick", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 23, name = "stairs:slab_mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 3, name = "default:torch_wall", prob = 254},
		__, __, __, __, __, {param2 = 2, name = "default:torch_wall", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 1, name = "default:torch", prob = 254},
		__, __, __, {param2 = 1, name = "default:torch", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_cup", prob = 254},
		__, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_cup", prob = 254},
		__, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, T["W0L21"], {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		T["W0L23"], __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, {param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 1, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, T["Ld0S0"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:basket", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, T["Ld0S0"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		T["Ld0S0"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 1, name = "earthbuild:trapdoor_wattle_open", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_cup", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, __, __, {param2 = 21, name = "stairs:slab_mud_brick", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 20, name = "stairs:slab_mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, {param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 1, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		__, {param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:stair_cob", prob = 254},
		{param2 = 1, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_container", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_container", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		__, __, __, __, __, {param2 = 4, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:bottlegourd_container", prob = 254},
		__, __, __, __, __, {param2 = 4, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, T["W0L01"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform", prob = 254},
		{param2 = 4, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		T["W0L03"], __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:trapdoor_wattle_open", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 4, name = "default:ladder_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 4, name = "default:ladder_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, {param2 = 0, name = "default:fence_wood", prob = 254},
		__, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, T["W0L21"], {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 4, name = "default:ladder_wood", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 4, name = "default:torch_wall", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		T["W0L23"], __, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:trapdoor_wattle", prob = 254},
		{param2 = 2, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "earthbuild:cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, {param2 = 2, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:basket", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 3, name = "earthbuild:primitive_bed_top", prob = 254},
		{param2 = 3, name = "earthbuild:primitive_bed_bottom", prob = 254},
		{param2 = 0, name = "earthbuild:storage_pot", prob = 254},
		{param2 = 1, name = "earthbuild:primitive_bed_bottom", prob = 254},
		{param2 = 1, name = "earthbuild:primitive_bed_top", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:woven_mat", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, {param2 = 3, name = "stairs:slab_cob", prob = 254},
		{param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 2, name = "stairs:stair_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:stair_cob", prob = 254},
		{param2 = 2, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:stair_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		__, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "doors:door_wattle_a", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, __, __, {param2 = 1, name = "stairs:slab_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "doors:hidden", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 3, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:stick_platform_with_brush", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:supported_cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:wattle_loose", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		__, {param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 20, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 20, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 20, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		{param2 = 0, name = "earthbuild:cob", prob = 254},
		__, __, __, __, __, __, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		{param2 = 2, name = "stairs:stair_cob", prob = 254},
		{param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "earthbuild:mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 3, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 2, name = "stairs:slab_mud_brick", prob = 254},
		{param2 = 0, name = "stairs:slab_mud_brick", prob = 254},
		__, __, __, __, __, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, {param2 = 2, name = "stairs:slab_cob", prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, T["W0L02"], __, T["W0L02"], __, T["W0L02"], __, T["W0L02"], __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, T["W0L02"], __, T["W0L02"], __, T["W0L02"], __, T["W0L02"], __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, T["W0L20"], __, T["W0L20"], __, T["W0L20"], __, T["W0L20"], __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0, name = "air", prob = 254}
	},
	yslice_prob = {
		{prob = 254, ypos = 0},
		{prob = 254, ypos = 1},
		{prob = 254, ypos = 2},
		{prob = 254, ypos = 3},
		{prob = 254, ypos = 4},
		{prob = 254, ypos = 5},
		{prob = 254, ypos = 6},
		{prob = 254, ypos = 7},
		{prob = 254, ypos = 8},
		{prob = 254, ypos = 9},
		{prob = 254, ypos = 10},
		{prob = 254, ypos = 11},
		{prob = 254, ypos = 12},
		{prob = 254, ypos = 13},
		{prob = 254, ypos = 14},
		{prob = 254, ypos = 15},
		{prob = 254, ypos = 16},
		{prob = 254, ypos = 17},
		{prob = 254, ypos = 18},
		{prob = 254, ypos = 19}
	}
}