



local T = lib_towns.schems.T


--Air, Lava, and Water constants used throughout schematics
	local __ = T["_____"] or {name = "air", param2 = 0, prob = 254}

	local M0 = {param2 = 0,name = "orcinvasion:brick",prob = 254}
	local M1 = {param2 = 0,name = "default:cobble",prob = 254}

	local N0 = {param2 = 0,name = "default:desert_sand",prob = 254}

	local S0 = {param2 = 0, name = "stairs:stair_quartz", prob = 254}
	local S1 = {param2 = 1, name = "stairs:stair_quartz", prob = 254}
	local S2 = {param2 = 2, name = "stairs:stair_quartz", prob = 254}
	local S3 = {param2 = 3, name = "stairs:stair_quartz", prob = 254}
	local S5 = {param2 = 20, name = "stairs:stair_quartz", prob = 254}
	local S6 = {param2 = 21, name = "stairs:stair_quartz", prob = 254}
	local S7 = {param2 = 22, name = "stairs:stair_quartz", prob = 254}
	local S8 = {param2 = 23, name = "stairs:stair_quartz", prob = 254}

	local L0 = {param2 = 0, name = "stairs:slab_quartz", prob = 254}
	local L1 = {param2 = 1, name = "stairs:slab_quartz", prob = 254}
	local L2 = {param2 = 2, name = "stairs:slab_quartz", prob = 254}
	local L3 = {param2 = 3, name = "stairs:slab_quartz", prob = 254}
	local L5 = {param2 = 20, name = "stairs:slab_quartz", prob = 254}
	local L6 = {param2 = 21, name = "stairs:slab_quartz", prob = 254}
	local L7 = {param2 = 22, name = "stairs:slab_quartz", prob = 254}
	local L8 = {param2 = 23, name = "stairs:slab_quartz", prob = 254}

	local TC = T["TcN00"] or {name = "torch:torch_ceiling", param2 = 0, prob = 254}
	local TT = T["TrN00"] or {name = "torch:torch", param2 = 1, prob = 254}
	local T1 = T["TwF00"] or {name = "torch:torch_wall", param2 = 1, prob = 254}
	local T2 = T["TwN00"] or {name = "torch:torch_wall", param2 = 2, prob = 254}
	local T3 = T["TwE00"] or {name = "torch:torch_wall", param2 = 3, prob = 254}
	local T4 = T["TwS00"] or {name = "torch:torch_wall", param2 = 4, prob = 254}
	local T5 = T["TwW00"] or {name = "torch:torch_wall", param2 = 5, prob = 254}

	local X0 = {param2 = 0,name = "orcinvasion:spawner",prob = 254}
	local X1 = {param2 = 0,name = "orcinvasion:spawner2",prob = 254}

	local DD = T["ddddd"] or {name = "lib_materials:dirt", param2 = 0, prob = 254}
	local DG = T["ggggg"] or {name = "lib_materials:dirt_with_grass", param2 = 0, prob = 254}
	local GR = DG
	local G1 = T["G0m00"] or {name = "lib_materials:glass", param2 = 0, prob = 254}

	local FF = T["swsws"] or {name = "lib_materials:dirt_with_soil_wet", param2 = 0, prob = 254}
	local CC = T["_Crn5_"] or {name = "lib_ecology:plant_corn_5", param2 = 0, prob = 254}


	local F0 = T["Fu0N0"] or {name = "lib_forge:furnace", param2 = 0, prob = 254}
	local F1 = T["Fu0E0"] or {name = "lib_forge:furnace", param2 = 1, prob = 254}
	local F2 = T["Fu0S0"] or {name = "lib_forge:furnace", param2 = 2, prob = 254}
	local F3 = T["Fu0W0"] or {name = "lib_forge:furnace", param2 = 3, prob = 254}

	local C0 = T["Cs0N0"] or {name = "lib_chests:chest", param2 = 0, prob = 254}
	local C1 = T["Cs0E0"] or {name = "lib_chests:chest", param2 = 1, prob = 254}
	local C2 = T["Cs0S0"] or {name = "lib_chests:chest", param2 = 2, prob = 254}
	local C3 = T["Cs0W0"] or {name = "lib_chests:chest", param2 = 3, prob = 254}

	local L0 = T["Ld0N0"] or {name = "lib_climbing:ladder_wood", param2 = 0, prob = 254}
	local L1 = T["Ld0E0"] or {name = "lib_climbing:ladder_wood", param2 = 1, prob = 254}
	local L2 = T["Ld0S0"] or {name = "lib_climbing:ladder_wood", param2 = 2, prob = 254}
	local L3 = T["Ld0W0"] or {name = "lib_climbing:ladder_wood", param2 = 3, prob = 254}
	local L4 = T["Ld0D0"] or {name = "lib_climbing:ladder_wood", param2 = 4, prob = 254}
	local L5 = T["Ld0D1"] or {name = "lib_climbing:ladder_wood", param2 = 5, prob = 254}


return {
	size = {x = 17,y = 18,z = 17},
	data = {
		DD, DD, DD, DD, DD, DD, DD, DD, DD, DD, DD, DD, DD, DG, DD, DD, DD,
		DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG,
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,
		__, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, DD, DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DD, DD, DD, DG, DG, DG, DG, DG, {param2 = 0,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "default:pine_tree",prob = 254},
		DG, DG, DG, DG, DG, __, __, __, __, __, {param2 = 0,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "default:pine_tree",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DD, DD, DG, DG, DG, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, DG, DG, DG, __, __, __, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 3,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 0,name = "earthbuild:bottlegourd_container",prob = 254},
		{param2 = 1,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 1,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DG, DG, DG, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, DG, DG, __, __, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:basket",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:basket",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 3,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DG, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 2,name = "stairs:slab_thatch",prob = 254},
		{param2 = 3,name = "stairs:slab_thatch",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:bottlegourd_cup",prob = 254},
		{param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, DG, __, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:basket",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:basket",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 3,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 2,name = "stairs:slab_thatch",prob = 254},
		{param2 = 2,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		DG, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:basket",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:basket",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DG, {param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "stairs:slab_cob",prob = 254},
		__, __, __, {param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, {param2 = 0,name = "earthbuild:wattle",prob = 254},
		{param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, {param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,

--
		DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DG, {param2 = 3,name = "stairs:stair_drystack",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:hearth",prob = 254},
		{param2 = 3,name = "earthbuild:cob",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, __, {param2 = 2,name = "doors:door_wattle_b",prob = 254},
		__, __, __, __, __, __, {param2 = 0,name = "earthbuild:hearth_air",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, {param2 = 1,name = "doors:hidden",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 9,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 1,name = "earthbuild:trapdoor_wattle_open",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,
--

		DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DG, {param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, {param2 = 2,name = "stairs:slab_cob",prob = 254},
		{param2 = 3,name = "earthbuild:cob",prob = 254},
		{param2 = 3,name = "stairs:slab_cob",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, {param2 = 0,name = "earthbuild:wattle",prob = 254},
		{param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, {param2 = 0,name = "earthbuild:bottlegourd_cup",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, {param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 1,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:slab_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 3,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:bottlegourd_cup",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 1,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		DG, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:basket",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:basket",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 3,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DG, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		__, __, __, {param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "stairs:slab_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, DG, __, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:basket",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:basket",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 1,name = "stairs:slab_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DD, DG, DG, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "stairs:slab_cob",prob = 254},
		{param2 = 0,name = "earthbuild:storage_pot",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, DG, DG, __, __, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:bottlegourd_container",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:basket",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, {param2 = 2,name = "stairs:slab_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 3,name = "stairs:slab_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:compacted_dirt",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DD, DD, DG, DG, DG, DG, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:cob",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DG, DG, DG, DG, __, __, __, __, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 3,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 3,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 0,name = "earthbuild:basket",prob = 254},
		{param2 = 1,name = "earthbuild:primitive_bed_bottom",prob = 254},
		{param2 = 1,name = "earthbuild:primitive_bed_top",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		__, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		__, __, __, __, __, {param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, {param2 = 1,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:stick_platform",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 3,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, DD, DD, DD, {param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		DD, DD, DD, DD, DG, DG, DG, DG, DG, DG, {param2 = 2,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 2,name = "default:pine_tree",prob = 254},
		DG, DG, DG, DG, DG, __, __, __, __, __, {param2 = 2,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 0,name = "earthbuild:drystack",prob = 254},
		{param2 = 2,name = "default:pine_tree",prob = 254},
		__, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, {param2 = 2,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 2,name = "default:pine_tree",prob = 254},
		__, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 2,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 0,name = "earthbuild:wattle_and_daub",prob = 254},
		{param2 = 2,name = "default:pine_tree",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __,


		DD, DD, DG, DD, DD, DD, DD, DD, DD, DD, DD, DG, DD, DD, DD, DD, DD, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, DG, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, __, __, {param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		{param2 = 0,name = "earthbuild:thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, {param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		{param2 = 2,name = "stairs:stair_thatch",prob = 254},
		__, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __
	},
	yslice_prob = {
		{prob = 254,ypos = 0},
		{prob = 254,ypos = 1},
		{prob = 254,ypos = 2},
		{prob = 254,ypos = 3},
		{prob = 254,ypos = 4},
		{prob = 254,ypos = 5},
		{prob = 254,ypos = 6},
		{prob = 254,ypos = 7},
		{prob = 254,ypos = 8},
		{prob = 254,ypos = 9},
		{prob = 254,ypos = 10},
		{prob = 254,ypos = 11},
		{prob = 254,ypos = 12},
		{prob = 254,ypos = 13},
		{prob = 254,ypos = 14},
		{prob = 254,ypos = 15},
		{prob = 254,ypos = 16},
		{prob = 254,ypos = 17}
	}
}